'use client'
import './globals.css'
import {Inter} from 'next/font/google'
import MenuComponent from "@/components/MenuComponent";
import {Flowbite} from "flowbite-react";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body className={inter.className + " dark:bg-gray-900 dark:text-white"}>
                <MenuComponent />
                <div className="max-w-screen-xl mx-auto ">
                    {children}
                </div>
            </body>
        </html>
    )
}
